vuejs-translations/docs-pl

.github/workflows/ryu-cho.yml
Ryu Cho workflow is currently failing.
Added secrets to repo config, changes ryu-cho.yml to utilise them.
=> [fix] Update ryu-cho.yml

.vitepress/theme/index.ts
resolves #39 
Cherry picked from https://github.com/vuejs/docs/commit/43f0fb3effb9893b3010b7fc5fd0a0808552e293
=> chore: enable banner close

.gitignore, .vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
resolves #43
Cherry picked from https://github.com/vuejs/docs/commit/082ec4c47ed7d4cde91bba72b16d861bd58a321e
=>  Revert "add vueconf.us banner" (#43)

src/guide/components/v-model.md
resolves #49
Cherry picked from https://github.com/vuejs/docs/commit/cba9103acd3719cc954f41a6d6317d176171c78b
=> doc: update v-model.md, fixed what I believe to be an error (#49)

src/guide/extras/rendering-mechanism.md
resolves #56
Cherry picked from https://github.com/vuejs/docs/commit/a7d0726f7180c6a474bc13050d0ced8fd9cd68b0
=> fix: update example in guide/extras/rendering-mechanism (#56)

.github/CONTRIBUTING.md, README.md
Add CONTRIBUTING.md file
resolves #33
=> Add contributing guidelines for polish language

src/guide/components/v-model.md
resolves #106
Cherry picked from https://github.com/vuejs/docs/commit/5de2d1196f1fe86c03887c4b170da9c62c945311
=> Update playground example for v-model modifiers (#106)

src/guide/components/v-model.md, src/guide/essentials/forms.md
resolves #108
Cherry picked from https://github.com/vuejs/docs/commit/52797e0dc584d5ac603f86ab72dbba7efb7e0e73
=> docs(forms): capitalize title (#108)

src/api/component-instance.md
resolves #115
Cherry picked from https://github.com/vuejs/docs/commit/d6b50e88d0f48aff49a4f7074b6f71e6e088dd3f
=> docs: fix $el type in documentation to 'any' (#115)

src/guide/reusability/composables.md, src/guide/reusability/custom-directives.md, src/guide/reusability/plugins.md
=> docs-#30: translate reusability

src/guide/scaling-up/sfc.md
* Translates first of the pages from https://github.com/monterail/vue3-docs-pl/issues/31 - which describes SFC files
=> [feat] Translate guide>scaling-up>sfc page

src/guide/scaling-up/tooling.md
* Translates second of the pages from https://github.com/monterail/vue3-docs-pl/issues/31 - which describes Vue tooling
=> [feat] Translate guide>scaling-up>tooling page

.vitepress/config.ts, src/guide/scaling-up/routing.md, src/guide/scaling-up/tooling.md
* Translates third of the pages from https://github.com/monterail/vue3-docs-pl/issues/31 - which describes Vue routing
=> [feat] Translate guide>scaling-up>routing page

src/guide/scaling-up/state-management.md
Translation of the state management guide page from https://github.com/monterail/vue3-docs-pl/issues/31
=> [feat] Translate guide>scaling-up>state-management page

src/guide/extras/animation.md, src/guide/extras/composition-api-faq.md, src/guide/extras/demos/AnimateWatcher.vue, src/guide/extras/demos/Colors.vue, src/guide/extras/demos/DisabledButton.vue, src/guide/extras/demos/ElasticHeader.vue, src/guide/extras/demos/spreadSheetStore.js, src/guide/extras/reactivity-in-depth.md, src/guide/extras/reactivity-transform.md, src/guide/extras/render-function.md, src/guide/extras/rendering-mechanism.md, src/guide/extras/ways-of-using-vue.md, src/guide/extras/web-components.md
Added translations to extra topics part.
=> feat/docs>feat/docs>extra-topics - added translations

src/guide/scaling-up/testing.md
Translation of page about tesing from scaling up guide https://github.com/monterail/vue3-docs-pl/issues/31
=> [feat] Translation of guide>scaling-up>testing page

netlify.toml, src/guide/essentials/class-and-style.md
resolves #158
Cherry picked from https://github.com/vuejs/docs/commit/899ec065e760e1f6e85fd545a41d01d59e3f2eb8
=> chore: bump node version on netlify (#158)

.vitepress/config.ts, src/guide/essentials/component-basics.md, src/guide/essentials/event-handling.md, src/guide/essentials/forms.md, src/guide/essentials/lifecycle.md, src/guide/essentials/list.md, src/guide/essentials/template-refs.md, src/guide/essentials/watchers.md
Translation of the remaining pages from https://github.com/vuejs-translations/docs-pl/issues/28
Cherry-picked from a different branch from @unnunhexium and adjusted based on some code conflicts.
=> [docs] Guide>essentials translation

.vitepress/config.ts, src/translations/index.md
=> [feat] Translation of docs>translations page

src/guide/built-ins/transition.md
resolves #185
Cherry picked from https://github.com/vuejs/docs/commit/2e07b40b2b55dfaa629143e9ffc56404027342ca
=> docs: fix blockquote language (#185)

.vitepress/config.ts, package.json, pnpm-lock.yaml, src/public/_redirects
resolves #201
Cherry picked from https://github.com/vuejs/docs/commit/96ec3f9105bebeb285e764aa23e584f737ab1be4
=> feat(docs): add a plugin to generate documentation for LLMs (#201)

src/api/composition-api-dependency-injection.md, src/api/sfc-script-setup.md, src/glossary/index.md, src/guide/built-ins/transition.md, src/guide/components/provide-inject.md, src/guide/essentials/computed.md, src/guide/essentials/template-refs.md, src/guide/extras/render-function.md, src/guide/extras/rendering-mechanism.md, src/guide/extras/web-components.md, src/guide/scaling-up/tooling.md
Resolve #200, #199, #198, #195, #192, #191, #189, #188, #187, #182
=> Head repo updates

src/guide/reusability/plugins.md
=> docs: improve phrasing for provide/inject in plugins.md (#3230)

src/guide/essentials/computed.md, src/guide/extras/animation.md
Adds commits 4e0fa3e and c80de28
=> [feat] Upstream updates

.vitepress/config.ts, .vitepress/theme/index.ts, .vitepress/theme/styles/index.css, .vitepress/theme/styles/vars.css, package.json, pnpm-lock.yaml, src/api/compile-time-flags.md, src/guide/extras/reactivity-transform.md, src/guide/extras/web-components.md, src/guide/quick-start.md, src/guide/reusability/plugins.md, src/guide/scaling-up/ssr.md, src/guide/scaling-up/testing.md, src/guide/scaling-up/tooling.md, src/tutorial/src/step-1/description.md
* feat: enhance code block & code group
* chore: fix line number
* chore: duplicate code line
=> feat: enhance code block & code group (#3235)
